### ISSUE TITLE
Support for sending authenticated requests

### ISSUE THREAD

**Issue by stof** [Pierstoval/SmokeTesting#2]
When building an app that requires authentication for everything, the smoke testing brings almost no value if done in anonymous mode (as it would just be testing the Symfony access control listener on all URLs).

I do have a similar kind of smoke testing in my own project (which is in that category), but I'm sending authenticated requests instead. And I can't find a hook for that in the existing trait.

**Comment by Pierstoval** [comment]
I just published [v0.4.0](https://github.com/Pierstoval/SmokeTesting/blob/main/CHANGELOG.md#v040) which should bring some change that might be interesting for your project, can you give me some feedback if it misses something? 😉

It misses one feature that I haven't worked on yet: customizing the `$client->request(...)` arguments before calling the request, so that you might also send an HTTP header with a cookie or an authorization header. But it's on the pipe :)

**Comment by Pierstoval** [comment]
> It misses one feature that I haven't worked on yet: customizing the `$client->request(...)` arguments before calling the request, so that you might also send an HTTP header with a cookie or an authorization header. But it's on the pipe :)

Hmm, now that I'm thinking about it, it can just be done in `beforeRequest()` via `$client->setServerParameter('HTTP_AUTHORIZATION', 'Bearer 0123456789')`, so I'm not sure whether I'll add anything for that. All the rest should be customizable already with the other trait

**Comment by Pierstoval** [comment]
Now @stof you can prepend an HTTP call before making the actual request with code like this:

```php
$this->runFunctionalTest(
    FunctionalTestData::withUrl('/authenticated_url/')
        ->withMethod('GET')
        ->withCallbackBeforeRequest(function (KernelBrowser $browser): void {
            $browser->request(
                method: 'POST', 
                uri: '/api/login',
                server: ['CONTENT_TYPE' => 'application/json'], 
                content: json_encode([
                    'username' => 'email@host.local',
                    'password' => 'some_password',
                ]),
            );
        })
        ->expectStatusCode(200)
);
```

The example figures a `$browser->request()` call, but the `$this` variable refers to the test object so you can call assertions or Symfony's WebTestCase helper methods.

Since the internal HTTP client has `$client->disableReboot()`, the kernel isn't restarted between requests, allowing potential stateful service usage like Session.

**Comment by Pierstoval** [comment]
Not allowed yet on the "all routes test", but available for the single functional tests helper 🚀

**Comment by Pierstoval** [comment]
Can be done with the `SmokeTestStaticRoutes` class by implementing this function:

```php
protected function beforeRequest(KernelBrowser $client, string $routeName, string $routePath): void
{
    // Here
}
```

Since there's the `$routeName` and `$routePath` variable, it's easy to filter by route name, prefix, or path prefix 👍
